### ISSUE TITLE
Two issues & have a patron or PayPal?

### ISSUE THREAD

**Issue by maxius4** [leonardoneumann/DimPlus#17]
First off, can I buy you a coffee? As this add-on helps a lot
The two errors I'm seeing is 

Lines 2 & 17 

#2 Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

#17 Error in event handler: TypeError: Error in invocation of tabs.remove([integer|array] tabIds, optional function callback): No matching signature.

Context
extension://jleepangkjclnelmkolfmbidkompbpii/_generated_background_page.html

Stack Trace
Background/background.js:17 (anonymous function)

**Comment by leonardoneumann** [comment]
Hello ! 
Thanks for wanting to support the project , I will be updating the readme with a coffeeapp/paypal link soon.
As for the reported console errors , I will be working on updating the extension to Manifest v3 in the next update. As for the other error , it happens when you close the popup window and reinitialize DIM. Neither of those errors cause the extension to stop working, so are you experiencing any other problem ? Do you notice usability issues ? Refreshing DIM page from time to time will keep the extension working.

**Comment by maxius4** [comment]
found this on line 107                                .rolls.find(r => r.column === colIndex - 1 && r.row === rowIndex) it was tossing an error

**Comment by maxius4** [comment]
Found the following Line14

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'sendMessage')



Context

https://beta.destinyitemmanager.com/4611686018490122635/d2/inventory

Stack Trace

Background/service.js:14 (anonymous function)

**Comment by maxius4** [comment]
Found the following Line 17 
Error in event handler: TypeError: Error in invocation of tabs.remove([integer|array] tabIds, optional function callback): No matching signature.



Context

extension://jleepangkjclnelmkolfmbidkompbpii/_generated_background_page.html

Stack Trace

Background/background.js:17 (anonymous function)

**Comment by maxius4** [comment]
Found the following line 107
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'rolls')



Context

https://beta.destinyitemmanager.com/4611686018490122635/d2/inventory

Stack Trace

DIM/communityrolls.js:104 (anonymous function)

**Comment by maxius4** [comment]
> 

sorry it took so long just little things here and there its working flawlessly i really wish this could be packed as an addon to dim does dim even allow addons in the app version?
