### ISSUE TITLE
Perk popularity rankings not displaying on v0.9

### ISSUE THREAD

**Issue by SquiIIiam** [leonardoneumann/DimPlus#23]
This issue was initially corrected specifically for crafted guns with the release of v0.9, but DIM updates since then seem to have spread the issue back to all guns.

**Comment by SquiIIiam** [comment]
Reiterating that this issue is still ongoing

**Comment by SquiIIiam** [comment]
> working a new extension that will solve these issues

Awesome, glad to hear you still have plans for this project since it's an excellent concept and I've been missing this functionality!

**Comment by m4j1n** [comment]
so happy to see your comment just a few days ago, great app cant wait for the new version/extension

**Comment by leonardoneumann** [comment]
One or two days for it to be ready

**Comment by m4j1n** [comment]
You are the man. There may not be many vocal people in the GitHub but I know this a huge service for the community. Thank you!!!

**Comment by mgibbonsjr** [comment]
I agree that this is big for the community. I don't think I would play destiny anymore without this plugin. Wault management is 100x easier due to your work. Thank you thank you thank you!

**Comment by leonardoneumann** [comment]
Thanks for your kind comments, they mean a lot.
I know the new dlc is up and this tool will be helpful, I'm just a little behind schedule. I'm at 80% of functionality, I just need to work on the UI a little bit and it will be done. As soon as I get a beta I'll publish it, for now what I can tell you is that it is a lot faster than the previous extension, and won't need almost any updates when dim changes layout since it handles its own side panel to display data.

**Comment by m4j1n** [comment]
Apologies if this feels PM-ish; how long you think im sure a few of us would gladly help with prelim testing ;)

**Comment by mgibbonsjr** [comment]
Glad to hear you are getting close! I have been checking daily over the last week to look for the beta push =) Thanks for all the hard work!

**Comment by leonardoneumann** [comment]
https://github.com/leonardoneumann/DimPlus/releases/tag/public_release_1.0a
